MySQL:
  host: localhost
  port: 3306
  user: root
  database: minecraft
  password: ''


Discord:
  token: CLIENTTOKEN
  game: Minecraft
  firstLinkCommands:
    - give %player% diamond

Roles:
  defaultrole: 7
  group:
    admin: 1
    moderator: 2
    premium: 1
Messages:
  verify: '&7[&aDiscord&7]&r Please send this message to our bot "!verify %code%"'
  unverify: '&7[&aDiscord&7]&r Please send this message to our bot "!unlink %code%"'
  discordlink: '&7[&aDiscord&7]&r Discord invite: asdasdasd'
  running: '&7[&aDiscord&7]&c There is already a verfication request in our system for you your code was %code%'
  verified: '&7[&aDiscord&7]&c You are already verified use /discord unlink to unlink your account'
  notverified: '&7[&aDiscord&7]&c You are not verified use /discord verify to verify your account'
  linked: '&7[&aDiscord&7]&c Successfully linked'
  unlinked: '&7[&aDiscord&7]&c Successfully unlinked'
  invalidcode: 'Your code was invalid!'
  success: 'Successfully linked with **%discord%**'
  successUnlink: 'Successfully unlinked with **%discord%**'
  updated: '&7[&aDiscord&7]&c Successfully updated discord ranks'
  help: 'Commands: %nl /discord verify %nl /discord unlink %nl /discord update'
  clickToCopy: 'Click to copy!'

